### ISSUE TITLE
Henlo

### ISSUE THREAD

**Issue by regdocs** [WhiteFang033/Nature#1]
Hi

**Comment by WhiteFang033** [comment]
Hola!
![3601-cat-wink](https://user-images.githubusercontent.com/50671673/189477054-6a6bf221-7dfb-4b39-b47b-3fcac3fd950f.png)

**Comment by regdocs** [comment]
A copypasta is a block of text that is [copied and pasted](https://en.wikipedia.org/wiki/Cut,_copy,_and_paste) across the [Internet](https://en.wikipedia.org/wiki/Internet) by individuals through [online forums](https://en.wikipedia.org/wiki/Online_forum) and [social networking](https://en.wikipedia.org/wiki/Social_networking) websites. Copypastas are said to be similar to [spam](https://en.wikipedia.org/wiki/Spamming)[[1]](https://en.wikipedia.org/wiki/Copypasta#cite_note-Techopedia-1) as they are often used to annoy other users and disrupt online discourse.

Thanks for resolving my issue!
